### ISSUE TITLE
EMP not affecting anything?

### ISSUE THREAD

**Issue by Breadabix** [calclavia/ICBM-Classic#6]
I have been testing out ICBM classic for bugs and server crashing items and have found that the EMP does not drain the power from anything. This includes Big reactors, thermal expansion, mekanism, redstone armoury/arsenal, enderIO, quantumflux, simply jetpacks, mffs and maybe others I dont remember. Basically it fails at its job. Could this be fixed?

**Comment by Breadabix** [comment]
Sorry wrong version of the mod :/

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM
https://github.com/BuiltBrokenModding/ICBM-Classic


Also no problem a lot of people have been mistaking this issue track @calclavia needs to close it to preven this problem. As well update the readme

**Comment by Breadabix** [comment]
I made an issue on the proper page
